version: "3"

services:
#  api-server:
#    image: yanrun/api:latest
#    env_file:
#      - .env
#    ports:
#      - "3000:3000"
#    depends_on:
#      - postgres
#      - mongo
#    networks:
#      - lan

#  web:
#    image: yanrun/web:latest
#    build:
#      context: .
#      dockerfile: ./src/client/Dockerfile
#    env_file:
#      - .env
#    ports:
#      - "80:5000"
#    depends_on:
#      - postgres
#      - mongo
#      - api-server
#    networks:
#      - lan

  postgres:
    container_name: postgres_container
    image: postgres:13.2-alpine
    restart: always
    env_file:
      - .env
    volumes:
      - ./database/postgresdb:/var/lib/postgresql/data
#      - ./database/migrations/postgres/:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"
    networks:
      - lan

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    restart: always
    env_file:
      - .env
    volumes:
      - ./database/pgadmin:/root/.pgadmin
    ports:
      - "8080:80"
    depends_on:
      - postgres
    networks:
      - lan

  mongo:
    container_name: mongo_container
    image: mongo
    restart: always
    env_file:
      - .env
    volumes:
      - ./database/mongodb:/data/db
    ports:
      - "27017:27017"
    networks:
      - lan

networks:
  lan:
    driver: bridge
