name: CI/CD into Yandex.Cloud

on:
  push:
    branches: [ develop ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push API
        uses: docker/build-push-action@v2.4.0
        with:
          context: .
          file: ./src/api-server/Dockerfile
          tags: dubaidev/yanrun-api:latest
          push: true

      - name: Build and push WEB
        uses: docker/build-push-action@v2.4.0
        with:
          context: .
          file: ./src/client/Dockerfile
          tags: dubaidev/yanrun-web:latest
          push: true

      - name: Create SSH private key file
        run: echo "${{ secrets.SSH_PRIVATE_KEY }}" > id_rsa && sudo chmod 400 id_rsa
      - name: Update known hosts
        run: mkdir ~/.ssh && echo "${{ secrets.KNOWN_HOSTS }}" > ~/.ssh/known_hosts
      - name: SSH and update containers
        run: ssh ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_IP }} -i id_rsa "cd /apps/yanrun/ && sudo docker-compose pull web api-server && (sudo docker-compose stop || true) && sudo docker-compose up -d"
